### PR TITLE
Alternate link relation

### LINKED ISSUE #232: Add support for the alternate link relation
Please add support for downloading the certificate using the [alternate link relation](https://tools.ietf.org/html/rfc8555#section-7.4.2), like certbot provides with the [--preferred-chain](https://github.com/certbot/certbot/issues/6971) option

### PR DESCRIPTION
**Pull request by wiggisser**
## Description

fixes #232 

This PR adds support for the alternate link relation to download the certificate rooted at a preferred trust anchor.

I updated the existing tests so that they can be compiled again and are still passing. ~~But I honestly have no clue how to update testing for the new parameter.~~ And I finally also managed to create a test. 

## Checklist

- [X] All tests are passing
- [X] New tests were created to address changes in pr (and tests are passing)
- [X] Updated README and/or documentation, if necessary

Thanks for contributing!

### CODE REVIEW

**Comment by webprofusion-chrisc** [comment]
Thanks very much for contributing this. I'll check it out. @fszlin are you happy for this to be merged?

**Comment by wiggisser** [comment]
I also wanted to embed the root for "fake le root x2", but I can't find it anywhere

**Comment by webprofusion-chrisc** [comment]
Thanks, the only problem with embedding the roots is that there will eventually be many (free) ACME CAs, currently there are 3 that I know of (Let's Encrypt, BuyPass GO and ZeroSSL) and really an ACME client library shouldn't favour one, instead there should be a common pattern for discovering available roots, but that's a topic for a different day :)

**Comment by webprofusion-chrisc** [comment]
Tested and works for me.

**Pull request merged**
